Repository Sharing-DSM/Sharing_iOS, pull requests merged in 2023-11, with the labels that each got.

#35 🔀 :: (#34) 앱 아이콘 추가 및 기타 버그 수정
  Application/Resources/Colors.xcassets/AppIcon.appiconset/100.png
  Application/Resources/Colors.xcassets/AppIcon.appiconset/1024.png
  Application/Resources/Colors.xcassets/AppIcon.appiconset/114.png
  Application/Resources/Colors.xcassets/AppIcon.appiconset/120.png
  Application/Resources/Colors.xcassets/AppIcon.appiconset/144.png
  Application/Resources/Colors.xcassets/AppIcon.appiconset/152.png
  Application/Resources/Colors.xcassets/AppIcon.appiconset/167.png
  Application/Resources/Colors.xcassets/AppIcon.appiconset/180.png
  Application/Resources/Colors.xcassets/AppIcon.appiconset/20.png
  Application/Resources/Colors.xcassets/AppIcon.appiconset/29.png
  Application/Resources/Colors.xcassets/AppIcon.appiconset/40.png
  Application/Resources/Colors.xcassets/AppIcon.appiconset/50.png
  Application/Resources/Colors.xcassets/AppIcon.appiconset/57.png
  Application/Resources/Colors.xcassets/AppIcon.appiconset/58.png
  Application/Resources/Colors.xcassets/AppIcon.appiconset/60.png
  Application/Resources/Colors.xcassets/AppIcon.appiconset/72.png
  Application/Resources/Colors.xcassets/AppIcon.appiconset/76.png
  Application/Resources/Colors.xcassets/AppIcon.appiconset/80.png
  Application/Resources/Colors.xcassets/AppIcon.appiconset/87.png
  Application/Resources/Colors.xcassets/AppIcon.appiconset/Contents.json
  Projects/Presentation/Sources/Scene/Auth/Signup/SignupViewController.swift
  Projects/Presentation/Sources/Scene/Tabs/Home/HomeViewController.swift
Labels: 버그수정, 자잘한수정

#28 🔀 :: (27) 마이페이지 구현
  Modules/AppNetwork/Sources/Profile/Remote/API/ProfileAPI.swift
  Modules/AppNetwork/Sources/Profile/Remote/Error/ProfileError.swift
  Modules/SharingKit/Resources/Image.xcassets/ProfilePlus.imageset/Contents.json
  Modules/SharingKit/Resources/Image.xcassets/ProfilePlus.imageset/profilePlus.svg
  Modules/SharingKit/Resources/Image.xcassets/calendarIcon.imageset/Contents.json
  Modules/SharingKit/Resources/Image.xcassets/calendarIcon.imageset/icon_calendar.svg
  Modules/SharingKit/Resources/Image.xcassets/checkmarkIcon.imageset/Contents.json
  Modules/SharingKit/Resources/Image.xcassets/checkmarkIcon.imageset/checkmarkIcon.svg
  Modules/SharingKit/Resources/Image.xcassets/folderIcon.imageset/Contents.json
  Modules/SharingKit/Resources/Image.xcassets/folderIcon.imageset/icon_folder.svg
  Modules/SharingKit/Resources/Image.xcassets/profileImage.imageset/Contents.json
  Modules/SharingKit/Resources/Image.xcassets/profileImage.imageset/sharingProfile.svg
  Projects/AppFlow/Sources/App/AppFlow.swift
  Projects/AppFlow/Sources/ProfileFlow/ProfileFlow.swift
  Projects/AppFlow/Sources/StepperDI.swift
  Projects/AppFlow/Sources/TestFlow/TestFlow.swift
  Projects/Core/Sources/Util/SharingStep.swift
  Projects/Data/Sources/Profile/DTO/CompleteScheduleDTO.swift
  Projects/Data/Sources/Profile/DTO/CompleteScheduleListDTO.swift
  Projects/Data/Sources/Profile/DTO/UserProfileDTO.swift
  Projects/Data/Sources/Profile/DataSource/ProfileDataSource.swift
  Projects/Data/Sources/Profile/Repository/ProfileRepositoryImpl.swift
  Projects/Data/Sources/ServiceDI.swift
  Projects/Domain/Sources/profile/Entity/CompleteScheduleEntity.swift
  Projects/Domain/Sources/profile/Entity/UserProfileEntity.swift
  Projects/Domain/Sources/profile/Repository/ProfileRepository.swift
  Projects/Domain/Sources/profile/UseCase/FetchUserProfileUseCase.swift
  Projects/Domain/Sources/profile/UseCase/PatchUserProfileUseCase.swift
  Projects/Domain/Sources/profile/UseCase/PostScheduleUseCase.swift
  Projects/Presentation/Sources/Scene/Schedule/Edit/EditScheduleViewController.swift
  Projects/Presentation/Sources/Scene/Schedule/Edit/EditScheduleViewModel.swift
  Projects/Presentation/Sources/Scene/Schedule/Post/CreatScheculeViewController.swift
  Projects/Presentation/Sources/Scene/Schedule/Post/CreateSheduleViewModel.swift
  Projects/Presentation/Sources/Scene/Schedule/ScheduleViewController.swift
  Projects/Presentation/Sources/Scene/Tabs/Profile/Cell/ScheduleTableViewCell.swift
  Projects/Presentation/Sources/Scene/Tabs/Profile/ProfileEditViewController.swift
  Projects/Presentation/Sources/Scene/Tabs/Profile/ProfileEditViewModel.swift
  Projects/Presentation/Sources/Scene/Tabs/Profile/ProfileViewController.swift
  Projects/Presentation/Sources/Scene/Tabs/Profile/ProfileViewModel.swift
  Projects/Presentation/Sources/Scene/Tabs/ProfileViewController.swift
Labels: 기능추가

#37 🔀 :: (#32) 주변 게시물 조회 기능 추가
  Modules/AppNetwork/Sources/Post/Remote/API/PostAPI.swift
  Projects/AppFlow/Sources/StepperDI.swift
  Projects/Core/Sources/Util/Extension/CLLocationManager+toLocation.swift
  Projects/Data/Sources/Post/DTO/SurroundPostDTO.swift
  Projects/Data/Sources/Post/DataSource/PostDataSource.swift
  Projects/Data/Sources/Post/Repository/PostRepositoryImpl.swift
  Projects/Data/Sources/ServiceDI.swift
  Projects/Domain/Sources/Post/Entity/PopularityPostEntity.swift
  Projects/Domain/Sources/Post/Entity/SurroundPostEntity.swift
  Projects/Domain/Sources/Post/Repository/PostRepository.swift
  Projects/Domain/Sources/Post/UseCase/FetchSurroundingPostUseCase.swift
  Projects/Presentation/Sources/Scene/Tabs/Map/MapPostViewController.swift
  Projects/Presentation/Sources/Scene/Tabs/Map/MapViewController.swift
  Projects/Presentation/Sources/Scene/Tabs/Map/MapViewModel.swift
Labels: 기능추가

#48 🔀 :: (#47) 긴급 게시물 기능 추가
  Modules/AppNetwork/Sources/Post/Remote/API/PostAPI.swift
  Modules/AppNetwork/Sources/Profile/Remote/API/ProfileAPI.swift
  Projects/AppFlow/Sources/App/AppFlow.swift
  Projects/AppFlow/Sources/StepperDI.swift
  Projects/AppFlow/Sources/TestFlow/TestFlow.swift
  Projects/Data/Sources/Post/DTO/CommonPostDTO.swift
  Projects/Data/Sources/Post/DataSource/PostDataSource.swift
  Projects/Data/Sources/Post/Repository/PostRepositoryImpl.swift
  Projects/Data/Sources/ServiceDI.swift
  Projects/Domain/Sources/Chat/UseCase/ChattingUseCase.swift
  Projects/Domain/Sources/Chat/UseCase/CreateChatRoomUseCase.swift
  Projects/Domain/Sources/Chat/UseCase/FetchChatRoomListUseCase.swift
  Projects/Domain/Sources/Post/Entity/SurroundPostEntity.swift
  Projects/Domain/Sources/Post/Repository/PostRepository.swift
  Projects/Domain/Sources/Post/UseCase/CreatePostUseCase.swift
  Projects/Domain/Sources/Post/UseCase/DeletePostUseCase.swift
  Projects/Domain/Sources/Post/UseCase/FetchEmergencyPostUseCase.swift
  Projects/Domain/Sources/Post/UseCase/FetchPostDetailUseCase.swift
  Projects/Domain/Sources/Post/UseCase/FetchSurroundingPostUseCase.swift
  Projects/Domain/Sources/Post/UseCase/PatchPostUseCase.swift
  Projects/Presentation/Sources/Scene/Tabs/Home/Banner/BannerContentView.swift
  Projects/Presentation/Sources/Scene/Tabs/Home/Banner/BannerView.swift
  Projects/Presentation/Sources/Scene/Tabs/Home/BannerView.swift
  Projects/Presentation/Sources/Scene/Tabs/Home/HomeViewController.swift
  Projects/Presentation/Sources/Scene/Tabs/Home/HomeViewModel.swift
  Projects/Presentation/Sources/Scene/Tabs/Map/MapViewModel.swift
Labels: 기능추가

#54 🔀 :: (#50) 신청 목록 조회 기능 추가
  Modules/AppNetwork/Sources/Post/Remote/API/PostAPI.swift
  Projects/AppFlow/Sources/App/AppFlow.swift
  Projects/AppFlow/Sources/HomeFlow/HomeFlow.swift
  Projects/AppFlow/Sources/StepperDI.swift
  Projects/AppFlow/Sources/TestFlow/TestFlow.swift
  Projects/Core/Sources/Util/SharingStep.swift
  Projects/Data/Sources/Post/DTO/ApplicantListDTO.swift
  Projects/Data/Sources/Post/DataSource/PostDataSource.swift
  Projects/Data/Sources/Post/Repository/PostRepositoryImpl.swift
  Projects/Data/Sources/ServiceDI.swift
  Projects/Domain/Sources/Post/Entity/ApplicantListEntity.swift
  Projects/Domain/Sources/Post/Repository/PostRepository.swift
  Projects/Domain/Sources/Post/UseCase/FetchApplicantListUseCase.swift
  Projects/Presentation/Sources/Scene/Applicant/ApplicantViewController.swift
  Projects/Presentation/Sources/Scene/Applicant/ApplicantViewModel.swift
  Projects/Presentation/Sources/Scene/Applicant/Cell/ApplicantListCollectionViewCell.swift
  Projects/Presentation/Sources/Scene/Post/Detail/PostDetailViewController.swift
  Projects/Presentation/Sources/Scene/Post/Detail/PostDetailViewModel.swift
Labels: 기능추가

#55 🔀 :: (#51) 자원봉사 신청 기능 구현
  Modules/AppNetwork/Sources/Post/Remote/API/PostAPI.swift
  Modules/AppNetwork/Sources/Post/Remote/Error/PostError.swift
  Projects/AppFlow/Sources/HomeFlow/HomeFlow.swift
  Projects/AppFlow/Sources/StepperDI.swift
  Projects/Data/Sources/Post/DataSource/PostDataSource.swift
  Projects/Data/Sources/Post/Repository/PostRepositoryImpl.swift
  Projects/Data/Sources/ServiceDI.swift
  Projects/Domain/Sources/Post/Repository/PostRepository.swift
  Projects/Domain/Sources/Post/UseCase/PostApplicationVolunteerUseCase.swift
  Projects/Presentation/Sources/Scene/Post/Detail/PostDetailViewController.swift
  Projects/Presentation/Sources/Scene/Post/Detail/PostDetailViewModel.swift
Labels: 기능추가

#57 🔀 :: (#56) Alert 디자인 변경
  Projects/AppFlow/Sources/AuthFlow/AuthFlow.swift
  Projects/AppFlow/Sources/HomeFlow/HomeFlow.swift
  Projects/AppFlow/Sources/MapFlow/MapFlow.swift
  Projects/Presentation/Sources/Scene/Alert/AlertViewController.swift
Labels: 자잘한수정

#53 🔀 :: (#43) 프로필 사진 변경, 관심지역 설정, 관심지역 불러오기
  Application/SuportingFile/Info.plist
  Modules/AppNetwork/Sources/Post/Remote/API/PostAPI.swift
  Modules/AppNetwork/Sources/Profile/Remote/API/ProfileAPI.swift
  Projects/AppFlow/Sources/ProfileFlow/ProfileFlow.swift
  Projects/AppFlow/Sources/StepperDI.swift
  Projects/Core/Sources/Util/SharingStep.swift
  Projects/Data/Sources/Post/DTO/AreaOfInterestPostDTO.swift
  Projects/Data/Sources/Post/DataSource/PostDataSource.swift
  Projects/Data/Sources/Post/Repository/PostRepositoryImpl.swift
  Projects/Data/Sources/Profile/DTO/CompleteScheduleDTO.swift
  Projects/Data/Sources/Profile/DTO/UnCompleteScheduleDTO.swift
  Projects/Data/Sources/Profile/DTO/UploadImageResponseDTO.swift
  Projects/Data/Sources/Profile/DTO/UserProfileDTO.swift
  Projects/Data/Sources/Profile/DataSource/ProfileDataSource.swift
  Projects/Data/Sources/Profile/Repository/ProfileRepositoryImpl.swift
  Projects/Data/Sources/ServiceDI.swift
  Projects/Domain/Sources/Post/Entity/AreaOfInterestPostEntity.swift
  Projects/Domain/Sources/Post/Repository/PostRepository.swift
  Projects/Domain/Sources/Post/UseCase/FetchAreaOfInteresPostUseCase.swift
  Projects/Domain/Sources/profile/Entity/UploadImageResponseEntity.swift
  Projects/Domain/Sources/profile/Entity/UserProfileEntity.swift
  Projects/Domain/Sources/profile/Repository/ProfileRepository.swift
  Projects/Domain/Sources/profile/UseCase/DeleteScheduleUseCase.swift
  Projects/Domain/Sources/profile/UseCase/SetAreaOfInterestUseCase.swift
  Projects/Domain/Sources/profile/UseCase/UploadImageUseCase.swift
  Projects/Presentation/Sources/Scene/Schedule/Cell/ScheduleTableViewCell.swift
  Projects/Presentation/Sources/Scene/Schedule/Post/CreateSheduleViewModel.swift
  Projects/Presentation/Sources/Scene/Schedule/ScheduleViewController.swift
  Projects/Presentation/Sources/Scene/Schedule/ScheduleViewModel.swift
  Projects/Presentation/Sources/Scene/Tabs/Home/HomeViewController.swift
  Projects/Presentation/Sources/Scene/Tabs/Home/HomeViewModel.swift
  Projects/Presentation/Sources/Scene/Tabs/Profile/Edit/ProfileEditViewController.swift
  Projects/Presentation/Sources/Scene/Tabs/Profile/Edit/ProfileEditViewModel.swift
  Projects/Presentation/Sources/Scene/Tabs/Profile/ProfileViewController.swift
  Projects/Presentation/Sources/Scene/Tabs/Profile/ProfileViewModel.swift
  Projects/Presentation/Sources/Scene/Tabs/Profile/SetAreaOfInterest/SetAreaOfInterestViewController.swift
  Projects/Presentation/Sources/Scene/Tabs/Profile/SetAreaOfInterest/SetAreaOfIntrestViewModel.swift
Labels: 기능추가

#66 🔀 :: (#59) 프로필 사진 연결
  Modules/SharingKit/Sources/Extension/Image/UIimage+.swift
  Projects/Data/Sources/Chat/DTO/ChatListDTO.swift
  Projects/Domain/Sources/Chat/Entity/ChatListEntity.swift
  Projects/Presentation/Sources/Scene/Applicant/Cell/ApplicantListCollectionViewCell.swift
  Projects/Presentation/Sources/Scene/Tabs/Chat/Cell/ChatTableViewCell.swift
  Projects/Presentation/Sources/Scene/Tabs/Chat/ChatViewController.swift
  Projects/Presentation/Sources/Scene/Tabs/Chat/ChatViewModel.swift
Labels: 자잘한수정

#67 🔀 :: (#58) 로딩 기능 추가
  Modules/SharingKit/Sources/Button/FillButton.swift
  Projects/Presentation/Sources/Scene/Auth/Login/LoginViewController.swift
  Projects/Presentation/Sources/Scene/Auth/Login/LoginViewModel.swift
Labels: 자잘한수정

#68 🔀 :: (#62) Flow 구조 리팩토링
  Projects/AppFlow/Sources/ApplyHistroy/ApplyHistroyFlow.swift
  Projects/AppFlow/Sources/HomeFlow/HomeFlow.swift
  Projects/AppFlow/Sources/MyPost/MyPostFlow.swift
  Projects/AppFlow/Sources/PostFlow/PostFlow.swift
  Projects/AppFlow/Sources/ProfileFlow/ProfileFlow.swift
  Projects/AppFlow/Sources/Schedule/ScheduleFlow.swift
  Projects/AppFlow/Sources/TabsFlow/TabFlow.swift
  Projects/Core/Sources/Util/Extension/DateFormatter.swift
  Projects/Core/Sources/Util/SharingStep.swift
  Projects/Data/Sources/Profile/DTO/UnCompleteScheduleDTO.swift
  Projects/Presentation/Sources/Scene/Schedule/Cell/ScheduleTableViewCell.swift
  Projects/Presentation/Sources/Scene/Schedule/ScheduleViewModel.swift
Labels: 리팩토링

#74 🔀 :: (#73) 버그 수정 및 기타 수정
  Projects/AppFlow/Sources/MapFlow/MapFlow.swift
  Projects/AppFlow/Sources/ProfileFlow/ProfileFlow.swift
  Projects/AppFlow/Sources/StepperDI.swift
  Projects/AppFlow/Sources/TabsFlow/TabFlow.swift
  Projects/Presentation/Sources/Scene/Adderss/AddressHelperViewController.swift
  Projects/Presentation/Sources/Scene/Adderss/AddressViewModel.swift
  Projects/Presentation/Sources/Scene/Post/Edit/PostEditViewController.swift
  Projects/Presentation/Sources/Scene/Post/Write/PostWriteViewController.swift
  Projects/Presentation/Sources/Scene/Tabs/Map/MapPostViewController.swift
  Projects/Presentation/Sources/Scene/Tabs/Map/MapViewController.swift
  Projects/Presentation/Sources/Scene/Tabs/Map/MapViewModel.swift
  Projects/Presentation/Sources/Scene/Tabs/Profile/ApplyHistory/ApplyHistoryViewController.swift
  Projects/Presentation/Sources/Scene/Tabs/Profile/ProfileViewController.swift
  Projects/Presentation/Sources/Scene/Tabs/Profile/ProfileViewModel.swift
Labels: 버그수정, 자잘한수정, 리팩토링
